name: easyboot_router
description: EasyBoot router package.
# version: 1.0.0
# homepage: https://www.ranyunlong.com/easyboot/router
# author: RanYunlong <849291425@qq.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  path: ^1.6.0
  path_to_regexp: ^0.2.1

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
